### ISSUE TITLE
comma discord

### ISSUE THREAD

**Issue by kubsztal** [AskAlice/AskAlice#1]
Why they have banned you?

**Comment by AskAlice** [comment]
![](https://emu.bz/2rK)

**Comment by AskAlice** [comment]
![](https://emu.bz/2rK)

**Comment by kubsztal** [comment]
Thanks, may I somehow join your discord?

**Comment by AskAlice** [comment]
here's a single use invite @kubsztal https://discord.gg/WCBbqXn5yE
